### ISSUE TITLE
Using External Database, Cannot Insert Null in ID Column in Oracle 12C

### ISSUE THREAD

**Issue by xx75vulcan** [Confluex/Zuul#84] opened 2015-11-12 21:01 UTC
I've downloaded and installed Zuul 1.5.1 using Tomcat7, on a Windows 2008 R2 machine and configured it to authenticate trough Active Directory.

After finding it authenticated through AD fine, I took the next step and changed the zule-data-config.xml file to use Oracle 12C instead of the default in-memory database.

I restarted Zuul and it created the tables in the Zuul schema, and Zuul started up.

I logged back into Zuul and the authentication page threw an error. 

The Zule.log file shows the following:
Error executing SQL INSERT INTO security_role (description, name) VALUES ('Guest', 'ROLE_GUEST'): ORA-01400: cannot insert NULL into ("ZUUL"."SECURITY_ROLE"."ID")

It appears the Zuul code is trying to insert into the table SECURITY_ROLE using only the columns "Description" and "Name" but failing to insert a value for the non-null field "ID".

**Comment by xx75vulcan** [comment] 2015-11-18 17:19
Hi,

Below are what the zuul db config looks like.
We commented out the default database, and added drivers for Oracle/Exadata.

As a temporary workaround, I created a database sequence and an insert
trigger for each of the tables that would generate the value for the
required "ID" column and that seemed to work. I just didn't know if it was
something I was comfortable using as a long term workaround, or if there
was a simple configuration change that I could make so that the "ID" column
was populated as part of Zuul's SQL Insert statements.

#------------ In Memory H2 Database ------------#

# Embedded databases which is useful for        #

# evaluation purposes. The data is wiped after  #

# server restart.                               #

#-----------------------------------------------#

#jdbc.zuul.url=jdbc:h2:mem:zuul

##jdbc.zuul.url=jdbc:h2:tcp://localhost/~/.zuul/data

#jdbc.zuul.generate.ddl=validate

#jdbc.zuul.username=sa

#jdbc.zuul.password=

#jdbc.zuul.driver=org.h2.Driver

#jdbc.zuul.dialect=org.hibernate.dialect.H2Dialect

#jdbc.zuul.validationQuery=select 1



#---------------- Exadata Database ----------------#

# Create a connection for Exadata                  #

#------------------------------------------------#

jdbc.zuul.url=jdbc:oracle:thin:@xxxxxxxx-scan:xxxxxx/xxxxxx.xxx.xx.xxx

jdbc.zuul.generate.ddl=none

jdbc.zuul.username=ZUUL

jdbc.zuul.password=xxxxxxxx

jdbc.zuul.driver=oracle.jdbc.OracleDriver

jdbc.zuul.dialect=org.hibernate.dialect.Oracle10gDialect

jdbc.zuul.validationQuery=select SYSDATE from DUAL

**Comment by psmith** [comment] 2015-11-18 23:17
For Oracle 12c, the liquibase version upgrade to the dependency may work.

Sorry, I'm working on some other stuff in my full time gig, so I haven't had time to setup a test. But, I'm expecting I'd have to change liquibase to make a sequence for oracle and/or upgrade the liquibase version.

**Comment by psmith** [comment] 2015-12-10 19:12
Closing issue as it is really a dupe of https://github.com/Confluex/Zuul/issues/64

**Closed by psmith** 2015-12-10 19:12 UTC
